version: '3.8'

services:
  frontend:
    container_name: auction-frontend
    ports:
      - 80:80
    image: auction-frontend
    build:
      context: frontend
    depends_on:
      - backend
  backend:
    container_name: auction-backend
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    image: auction-backend
    build:
      context: backend
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - backend/.env.prod
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
  mongodb:
    container_name: auction-mongodb
    ports:
      - 27017:27017
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    command: mongod --noauth

  mongo-admin:
    container_name: auction-mongo-admin
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb